-- APP-94: Store join token value for server-side validation.
-- The join token is a random UUID generated by the host, embedded in the QR
-- code URL.  Storing it lets the web join endpoint reject requests with an
-- invalid / forged token instead of relying solely on the session code.

alter table public.sessions
  add column if not exists join_token_value text null;
